import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";//comment later
import "../assets/css/global.css";
import "../assets/css/style.css";
import "../assets/css/responsive.css";
import "../assets/fonts/fonts.css";
import 'bootstrap/dist/css/bootstrap.css';
import Header from "@/shared/Component/header/page";
import { cookieToInitialState } from "wagmi";
import { config } from './wagmi/config'
import { headers } from "next/headers";
import WagmiProviderComp from "./wagmi/wagmi-provider";
import Providers from "@/shared/Component/header/providers/page";
import 'react-loading-skeleton/dist/skeleton.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rapid Dex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en" data-theme="dark">
    <head>
      {/* <meta charset="UTF-8"/> */}
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com"/>
      <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet"/>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"/>
    </head>    
    <body>
      <div className="body-bg"></div>
      <WagmiProviderComp initialState={initialState}>
      <Providers>
        <Header/>
        <div className="content-wrapper">
            {children}
        </div>
      </Providers>
      </WagmiProviderComp>
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
  );
}
